name: Start EC2
on:
  push:
    tags:
       - 'start-ec2-*'
jobs:
  start-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Start EC2
        id: start-ec2
        run: |
          aws ec2 start-instances \
            --instance-ids `aws ec2 describe-instances \
            --filters Name=tag:name,Values=ec2-deploy-cvwa \
            --query Reservations[].Instances[].InstanceId --output text`

  sleep-jobs:
    runs-on: ubuntu-latest
    needs: [deployment-codedeploy]
    steps:
       - name: Sleep for 1min
         uses: juliangruber/sleep-action@v1
         with:
           time: 1m

  ec2-public-ip-address:
    runs-on: ubuntu-latest
    needs: [sleep-jobs]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: EC2 IP address
        id: ip-address
        run: aws ec2 describe-instances --filters "Name=tag:name,Values=ec2-deploy-cvwa" --query "Reservations[].Instances[].PublicIpAddress"

